package service;

public enum ResultatEmprunt {
    SUCCES,
    UTILISATEUR_INEXISTANT,
    LIVRE_INEXISTANT,
    LIVRE_INDISPONIBLE,
    LIMITE_ETUDIANT_ATTEINTE,
    LIMITE_ENSEIGNANT_ATTEINTE,
    PENALITE_NON_REGLEE
}